// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

using Todo.Api.DataAccess;

#nullable disable

namespace api.DataAccess.Migrations.Mssql
{
    [DbContext(typeof(MssqlTodoContext))]
    partial class MssqlTodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.api.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Todo 1 Description",
                            IsCompleted = false,
                            Title = "Todo 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Todo 2 Description",
                            IsCompleted = true,
                            Title = "Todo 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Todo 3 Description",
                            IsCompleted = false,
                            Title = "Todo 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
